# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Ui_Files\ui_ConnectionDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ConnectionDialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(440, 150)
        self.VersionLabel = QtWidgets.QLabel(Dialog)
        self.VersionLabel.setGeometry(QtCore.QRect(385, 10, 45, 16))
        self.VersionLabel.setObjectName("VersionLabel")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(10, 10, 140, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.PortLine = QtWidgets.QLineEdit(Dialog)
        self.PortLine.setGeometry(QtCore.QRect(200, 80, 110, 25))
        self.PortLine.setMaxLength(5)
        self.PortLine.setObjectName("PortLine")
        self.ConnectButton = QtWidgets.QPushButton(Dialog)
        self.ConnectButton.setGeometry(QtCore.QRect(320, 80, 110, 25))
        self.ConnectButton.setObjectName("ConnectButton")
        self.ExitButton = QtWidgets.QPushButton(Dialog)
        self.ExitButton.setGeometry(QtCore.QRect(320, 110, 110, 25))
        self.ExitButton.setObjectName("ExitButton")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(193, 82, 10, 20))
        self.label.setObjectName("label")
        self.IPLine = QtWidgets.QLineEdit(Dialog)
        self.IPLine.setGeometry(QtCore.QRect(10, 80, 180, 25))
        self.IPLine.setMaxLength(15)
        self.IPLine.setObjectName("IPLine")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 55, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(200, 60, 55, 16))
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "OpenLChat - Connection"))
        self.VersionLabel.setText(_translate("Dialog", "Ver:1.0"))
        self.label_4.setText(_translate("Dialog", "OpenLChat"))
        self.ConnectButton.setText(_translate("Dialog", "Connect"))
        self.ExitButton.setText(_translate("Dialog", "Exit"))
        self.label.setText(_translate("Dialog", ":"))
        self.label_2.setText(_translate("Dialog", "IPv4:"))
        self.label_3.setText(_translate("Dialog", "Port:"))
