# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Ui_Files\ui_ConnectionDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ConnectionDialog(object):
    def setupUi(self, ConnectionDialog):
        ConnectionDialog.setObjectName("ConnectionDialog")
        ConnectionDialog.resize(440, 145)
        self.VersionLabel = QtWidgets.QLabel(ConnectionDialog)
        self.VersionLabel.setGeometry(QtCore.QRect(389, 9, 41, 21))
        self.VersionLabel.setObjectName("VersionLabel")
        self.label_4 = QtWidgets.QLabel(ConnectionDialog)
        self.label_4.setGeometry(QtCore.QRect(10, 10, 361, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.PortLine = QtWidgets.QLineEdit(ConnectionDialog)
        self.PortLine.setGeometry(QtCore.QRect(200, 80, 110, 25))
        self.PortLine.setMaxLength(5)
        self.PortLine.setObjectName("PortLine")
        self.ConnectButton = QtWidgets.QPushButton(ConnectionDialog)
        self.ConnectButton.setGeometry(QtCore.QRect(320, 80, 110, 25))
        self.ConnectButton.setObjectName("ConnectButton")
        self.label = QtWidgets.QLabel(ConnectionDialog)
        self.label.setGeometry(QtCore.QRect(193, 82, 10, 20))
        self.label.setObjectName("label")
        self.IPLine = QtWidgets.QLineEdit(ConnectionDialog)
        self.IPLine.setGeometry(QtCore.QRect(10, 80, 180, 25))
        self.IPLine.setMaxLength(15)
        self.IPLine.setObjectName("IPLine")
        self.label_2 = QtWidgets.QLabel(ConnectionDialog)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 121, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(ConnectionDialog)
        self.label_3.setGeometry(QtCore.QRect(200, 60, 91, 16))
        self.label_3.setObjectName("label_3")
        self.ExitButton = QtWidgets.QPushButton(ConnectionDialog)
        self.ExitButton.setGeometry(QtCore.QRect(320, 110, 110, 25))
        self.ExitButton.setObjectName("ExitButton")

        self.retranslateUi(ConnectionDialog)
        QtCore.QMetaObject.connectSlotsByName(ConnectionDialog)

    def retranslateUi(self, ConnectionDialog):
        _translate = QtCore.QCoreApplication.translate
        ConnectionDialog.setWindowTitle(_translate("ConnectionDialog", "OpenLChat - Connection"))
        self.VersionLabel.setText(_translate("ConnectionDialog", "Ver:1.0"))
        self.label_4.setText(_translate("ConnectionDialog", "OpenLChat"))
        self.ConnectButton.setText(_translate("ConnectionDialog", "Connect"))
        self.label.setText(_translate("ConnectionDialog", ":"))
        self.label_2.setText(_translate("ConnectionDialog", "IPv4:"))
        self.label_3.setText(_translate("ConnectionDialog", "Port:"))
        self.ExitButton.setText(_translate("ConnectionDialog", "Exit"))
