# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Ui_Files\ui_ConnectionMenu.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ConnectionWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(440, 150)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.IPLine = QtWidgets.QLineEdit(self.centralwidget)
        self.IPLine.setGeometry(QtCore.QRect(10, 80, 180, 25))
        self.IPLine.setMaxLength(15)
        self.IPLine.setObjectName("IPLine")
        self.PortLine = QtWidgets.QLineEdit(self.centralwidget)
        self.PortLine.setGeometry(QtCore.QRect(200, 80, 110, 25))
        self.PortLine.setMaxLength(5)
        self.PortLine.setObjectName("PortLine")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(193, 82, 10, 20))
        self.label.setObjectName("label")
        self.ConnectButton = QtWidgets.QPushButton(self.centralwidget)
        self.ConnectButton.setGeometry(QtCore.QRect(320, 80, 110, 25))
        self.ConnectButton.setObjectName("ConnectButton")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 55, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(200, 60, 55, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 10, 140, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.VersionLabel = QtWidgets.QLabel(self.centralwidget)
        self.VersionLabel.setGeometry(QtCore.QRect(385, 10, 45, 16))
        self.VersionLabel.setObjectName("VersionLabel")
        self.label.raise_()
        self.IPLine.raise_()
        self.PortLine.raise_()
        self.ConnectButton.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.VersionLabel.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "OpenLChat"))
        self.label.setText(_translate("MainWindow", ":"))
        self.ConnectButton.setText(_translate("MainWindow", "Connect"))
        self.label_2.setText(_translate("MainWindow", "IPv4:"))
        self.label_3.setText(_translate("MainWindow", "Port:"))
        self.label_4.setText(_translate("MainWindow", "OpenLChat"))
        self.VersionLabel.setText(_translate("MainWindow", "Ver:1.0"))
