# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Ui_Files\ui_MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(505, 354)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.SendButton = QtWidgets.QPushButton(self.centralwidget)
        self.SendButton.setGeometry(QtCore.QRect(420, 320, 75, 24))
        self.SendButton.setObjectName("SendButton")
        self.ExitButton = QtWidgets.QPushButton(self.centralwidget)
        self.ExitButton.setGeometry(QtCore.QRect(420, 10, 75, 24))
        self.ExitButton.setObjectName("ExitButton")
        self.ReloadButton = QtWidgets.QPushButton(self.centralwidget)
        self.ReloadButton.setGeometry(QtCore.QRect(420, 70, 75, 24))
        self.ReloadButton.setObjectName("ReloadButton")
        self.AboutButton = QtWidgets.QPushButton(self.centralwidget)
        self.AboutButton.setGeometry(QtCore.QRect(200, 70, 75, 24))
        self.AboutButton.setObjectName("AboutButton")
        self.NameEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.NameEdit.setGeometry(QtCore.QRect(10, 320, 80, 24))
        self.NameEdit.setObjectName("NameEdit")
        self.TextLine = QtWidgets.QLineEdit(self.centralwidget)
        self.TextLine.setGeometry(QtCore.QRect(100, 320, 310, 24))
        self.TextLine.setObjectName("TextLine")
        self.MessagesWidget = QtWidgets.QListWidget(self.centralwidget)
        self.MessagesWidget.setGeometry(QtCore.QRect(10, 10, 400, 290))
        self.MessagesWidget.setObjectName("MessagesWidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 305, 47, 13))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(100, 305, 55, 13))
        self.label_2.setObjectName("label_2")
        self.ReconnectButton = QtWidgets.QPushButton(self.centralwidget)
        self.ReconnectButton.setGeometry(QtCore.QRect(420, 40, 75, 24))
        self.ReconnectButton.setObjectName("ReconnectButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "IP:Port OpenLChat"))
        self.SendButton.setText(_translate("MainWindow", "Send"))
        self.ExitButton.setText(_translate("MainWindow", "Exit"))
        self.ReloadButton.setText(_translate("MainWindow", "Reload"))
        self.AboutButton.setText(_translate("MainWindow", "About"))
        self.label.setText(_translate("MainWindow", "Name:"))
        self.label_2.setText(_translate("MainWindow", "Message:"))
        self.ReconnectButton.setText(_translate("MainWindow", "Reconnect"))
